/** Adriatic species catalog — YouSea “Prebivalci tvojega morja” and zone references. */

const YOUSEA_BASE = 'https://www.yoursea.org/inhabitants-of-your-sea';

export const speciesCatalog = {
  'fan-mussel': {
    id: 'fan-mussel',
    nickname: 'Fan Mussel',
    slovenianName: 'Velika školjka (prstni školjka)',
    scientificName: 'Pinna nobilis',
    emoji: '🐚',
    status: 'Critically Endangered',
    iucnStatus: 'CR',
    statusColor: '#ef4444',
    fact: 'Europe’s largest bivalve; anchoring and disease have devastated Adriatic populations.',
    sourceUrl: `${YOUSEA_BASE}/velika-skoljka`,
  },
  'spider-crab': {
    id: 'spider-crab',
    nickname: 'Spider Crab',
    slovenianName: 'Veliki morski pajek',
    scientificName: 'Maja squinado',
    emoji: '🦀',
    status: 'Vulnerable',
    iucnStatus: 'VU',
    statusColor: '#f97316',
    fact: 'Long-legged reef crab; trawling and habitat loss threaten rocky-bottom communities.',
    sourceUrl: `${YOUSEA_BASE}/veliki-morski-pajek`,
  },
  'dusky-grouper': {
    id: 'dusky-grouper',
    nickname: 'Dusky Grouper',
    slovenianName: 'Modrak',
    scientificName: 'Epinephelus marginatus',
    emoji: '🐟',
    status: 'Endangered',
    iucnStatus: 'EN',
    statusColor: '#ef4444',
    fact: 'Slow-growing reef sentinel; overfishing has collapsed stocks across the northern Adriatic.',
    sourceUrl: `${YOUSEA_BASE}/modrak`,
  },
  seahorse: {
    id: 'seahorse',
    nickname: 'Seahorse',
    slovenianName: 'Morski konjiček',
    scientificName: 'Hippocampus hippocampus',
    emoji: '🐴',
    status: 'Data Deficient',
    iucnStatus: 'DD',
    statusColor: '#a78bfa',
    fact: 'Seagrass dweller highly sensitive to anchor damage and coastal sedimentation.',
    sourceUrl: `${YOUSEA_BASE}/morski-konjicek`,
  },
  posidonia: {
    id: 'posidonia',
    nickname: 'Neptune Grass',
    slovenianName: 'Posidonija (morska trava)',
    scientificName: 'Posidonia oceanica',
    emoji: '🌿',
    status: 'Protected habitat',
    iucnStatus: 'LC (species); habitat protected EU-wide',
    statusColor: '#22c55e',
    fact: 'Endemic Mediterranean seagrass — meadows shelter fish and turtles; one anchor scar can take decades to heal.',
    sourceUrl:
      'https://maritime-forum.ec.europa.eu/map-week-seagrass-meadows-posidonia-oceanica_en',
  },
  'loggerhead-turtle': {
    id: 'loggerhead-turtle',
    nickname: 'Loggerhead Turtle',
    slovenianName: 'Kareta (glavata)',
    scientificName: 'Caretta caretta',
    emoji: '🐢',
    status: 'Vulnerable',
    iucnStatus: 'VU',
    statusColor: '#f97316',
    fact: 'Uses Adriatic feeding grounds; boat strikes and entanglement are leading threats.',
    sourceUrl: `${YOUSEA_BASE}`,
  },
  'date-mussel': {
    id: 'date-mussel',
    nickname: 'Date Mussel',
    slovenianName: 'Datulj',
    scientificName: 'Lithophaga lithophaga',
    emoji: '🦪',
    status: 'Protected',
    iucnStatus: 'Protected (EU)',
    statusColor: '#22c55e',
    fact: 'Bores into limestone reefs; harvest and anchoring are prohibited in EU waters.',
    sourceUrl: `${YOUSEA_BASE}/datulj`,
  },
  'common-dolphin': {
    id: 'common-dolphin',
    nickname: 'Common Dolphin',
    slovenianName: 'Navadni delfin',
    scientificName: 'Delphinus delphis',
    emoji: '🐬',
    status: 'Least Concern',
    iucnStatus: 'LC',
    statusColor: '#38bdf8',
    fact: 'Regular visitor to the Gulf of Piran; noise and speed limits protect feeding pods.',
    sourceUrl: `${YOUSEA_BASE}/navadni-delfin`,
  },
  cladocora: {
    id: 'cladocora',
    nickname: 'Mediterranean Stone Coral',
    slovenianName: 'Sredozemska kamena korala',
    scientificName: 'Cladocora caespitosa',
    emoji: '🪸',
    status: 'Vulnerable',
    iucnStatus: 'VU',
    statusColor: '#f97316',
    fact: 'Only reef-building coral in the Mediterranean; colonizing the YouSea Cladocora structure in Piran Bay.',
    sourceUrl: `${YOUSEA_BASE}/sredozemska-kamena-korala`,
  },
  mytilus: {
    id: 'mytilus',
    nickname: 'Mediterranean Mussel',
    slovenianName: 'Sredozemska klapavica',
    scientificName: 'Mytilus galloprovincialis',
    emoji: '🦪',
    status: 'Least Concern',
    iucnStatus: 'LC',
    statusColor: '#38bdf8',
    fact: 'Key filter-feeder on the YouSea Mytilus aquaculture structure; indicator of water quality.',
    sourceUrl: `${YOUSEA_BASE}`,
  },
};

export function getSpecies(id) {
  return speciesCatalog[id] ?? null;
}

export function getSpeciesList(ids = []) {
  return ids.map((id) => getSpecies(id)).filter(Boolean);
}
